name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t twistedisles/todo-board:latest
    - name: publish
      run: |
        docker login -u twistedisles -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push twistedisles/todo-board:latest
